'''Sales Lead Generator

A sales team aggregates leads generated from various channels. Logs map Sales Agent Name to the Number of Leads generated in a week. Some logs have non-numeric entries for lead counts.

You must:

Combine the leads generated by Sales Agent Name.

If the lead count is not an integer, skip that entry and print:
"Invalid lead count skipped"

Display the final dictionary of total leads per agent.

Input Format:

A list of dictionaries:

[{Agent Name : Leads}, ...]

Output Format:

A single dictionary with values:

{Agent Name : Total Leads, ...}

Sample Input 1:
[{'Sarah': 15}, {'John': 10, 'Sarah': 5}]

Sample Output 1:
{'Sarah': 20, 'John': 10}'''

def manage_sales_leads(records):
    result = {}

    for record in records:
        for name, leads in record.items():
            if not isinstance(leads, int):
                print("Invalid lead count skipped")
                continue
            if name in result:
                result[name] += leads
            else:
                result[name] = leads

    print(result)

record = eval(input())
manage_sales_leads(record)